/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package studentenrollmentsystem;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asus
 */
public class CourseManagementWindow extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CourseManagementWindow.class.getName());

    private Connection getConnection() {
        return DBConnection.getConnection();
    }

    /**
     * Creates new form CourseManagementWindow
     */
    public CourseManagementWindow() {
        initComponents();

        jTable1.setBackground(java.awt.Color.WHITE);
        jScrollPane1.getViewport().setBackground(java.awt.Color.WHITE);
        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        jTable1.setShowVerticalLines(false);

        // This removes that gray block at the very bottom
        jScrollPane1.getViewport().setBackground(java.awt.Color.WHITE);

        // This removes the thin gray box around the entire table area
        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder());

        jTable1.setShowVerticalLines(false);

        // Create a clean, flat renderer for the Header
        javax.swing.table.DefaultTableCellRenderer headerRenderer = new javax.swing.table.DefaultTableCellRenderer();
        headerRenderer.setBackground(java.awt.Color.WHITE);
        headerRenderer.setForeground(new java.awt.Color(80, 80, 80)); // Matches your dark gray text
        headerRenderer.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 5, 10, 5)); // Adds padding, REMOVES vertical borders!
        headerRenderer.setHorizontalAlignment(javax.swing.JLabel.LEFT);

        // Apply this clean style to the table header
        jTable1.getTableHeader().setDefaultRenderer(headerRenderer);

        // Optional: Make the header a bit taller to look more modern
        jTable1.getTableHeader().setPreferredSize(new java.awt.Dimension(0, 35));

        javax.swing.table.DefaultTableCellRenderer leftRenderer = new javax.swing.table.DefaultTableCellRenderer();
        leftRenderer.setHorizontalAlignment(javax.swing.JLabel.LEFT);
        leftRenderer.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 5)); // 5px cushion

        // Loop through EVERY column and apply the left-alignment rule
        for (int i = 0; i < jTable1.getColumnCount(); i++) {
            jTable1.getColumnModel().getColumn(i).setCellRenderer(leftRenderer);
        }

        this.setLocationRelativeTo(null);

        ViewActionPerformed(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundedPanel1 = new studentenrollmentsystem.RoundedPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCourseName = new studentenrollmentsystem.RoundedTextField();
        Update = new studentenrollmentsystem.RoundedButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Add = new studentenrollmentsystem.RoundedButton();
        View = new studentenrollmentsystem.RoundedButton();
        Delete = new studentenrollmentsystem.RoundedButton();
        txtCredits = new studentenrollmentsystem.RoundedTextField();
        txtDescription = new studentenrollmentsystem.RoundedTextField();
        Enrollment = new studentenrollmentsystem.RoundedButton();
        Student = new studentenrollmentsystem.RoundedButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        roundedPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Course Management");
        roundedPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 12, 188, 34));

        jSeparator1.setForeground(new java.awt.Color(220, 220, 220));
        roundedPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 52, 688, 11));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setText("Course Details");
        roundedPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 69, 126, 39));

        jLabel3.setText("Description");
        roundedPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 186, 80, 34));

        jLabel4.setText("Course Name");
        roundedPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 134, 81, 34));

        jLabel5.setText("Credits");
        roundedPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 238, 60, 34));

        txtCourseName.addActionListener(this::txtCourseNameActionPerformed);
        roundedPanel1.add(txtCourseName, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 134, 170, 34));

        Update.setText("Update");
        Update.addActionListener(this::UpdateActionPerformed);
        roundedPanel1.add(Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 309, 100, 41));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Course Name", "Description", "Credits"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        roundedPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 69, 400, 330));

        Add.setText("Add");
        Add.addActionListener(this::AddActionPerformed);
        roundedPanel1.add(Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 309, 100, 41));

        View.setText("View");
        View.addActionListener(this::ViewActionPerformed);
        roundedPanel1.add(View, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 368, 100, 41));

        Delete.setText("Delete");
        Delete.addActionListener(this::DeleteActionPerformed);
        roundedPanel1.add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 368, 100, 41));

        txtCredits.addActionListener(this::txtCreditsActionPerformed);
        roundedPanel1.add(txtCredits, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 238, 170, 34));

        txtDescription.addActionListener(this::txtDescriptionActionPerformed);
        roundedPanel1.add(txtDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 186, 170, 34));

        Enrollment.setText("Enrollment Form");
        Enrollment.addActionListener(this::EnrollmentActionPerformed);
        roundedPanel1.add(Enrollment, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 410, 130, 40));

        Student.setText("Student Info");
        Student.addActionListener(this::StudentActionPerformed);
        roundedPanel1.add(Student, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, 130, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(roundedPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 729, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(roundedPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewActionPerformed
        try (Connection conn = getConnection(); Statement stmt = conn.createStatement(); ResultSet rs = stmt.executeQuery("SELECT * FROM Course")) {

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("course_id"),
                    rs.getString("course_name"),
                    rs.getString("course_description"),
                    rs.getInt("credits")
                });
            }

            clearFields();

            if (evt != null) {
                JOptionPane.showMessageDialog(this, "Course List Refreshed!");
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_ViewActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a course to delete from the table.");
            return;
        }

        int courseId = (int) jTable1.getValueAt(selectedRow, 0);

        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this course?", "Confirm Deletion", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            try (Connection conn = getConnection(); PreparedStatement pst = conn.prepareStatement("DELETE FROM Course WHERE course_id=?")) {

                pst.setInt(1, courseId);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Course Deleted Successfully!");
                ViewActionPerformed(null); // Refresh the table
                clearFields();
            } catch (SQLException e) {
                // This might trigger if a student is already enrolled in this course (Foreign Key constraint)
                JOptionPane.showMessageDialog(this, "Error deleting course: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_DeleteActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a course to update from the table.");
            return;
        }

// Get the course_id from the first column (index 0) of the selected row
        int courseId = (int) jTable1.getValueAt(selectedRow, 0);
        String query = "UPDATE Course SET course_name=?, course_description=?, credits=? WHERE course_id=?";

        try (Connection conn = getConnection(); PreparedStatement pst = conn.prepareStatement(query)) {

            pst.setString(1, txtCourseName.getText());
            pst.setString(2, txtDescription.getText());
            pst.setInt(3, Integer.parseInt(txtCredits.getText()));
            pst.setInt(4, courseId);

            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Course Updated Successfully!");
            ViewActionPerformed(null);
            clearFields();
        } catch (SQLException | NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error updating course. Make sure Credits is a valid number.");
        }
    }//GEN-LAST:event_UpdateActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:
        String query = "INSERT INTO Course (course_name, course_description, credits) VALUES (?, ?, ?)";
        try (Connection conn = getConnection(); PreparedStatement pst = conn.prepareStatement(query)) {

            pst.setString(1, txtCourseName.getText());
            pst.setString(2, txtDescription.getText());
            pst.setInt(3, Integer.parseInt(txtCredits.getText()));

            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Course Added Successfully!");
            ViewActionPerformed(null);
            clearFields();
        } catch (SQLException | NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error adding course.");
        }
    }//GEN-LAST:event_AddActionPerformed

    private void txtCreditsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCreditsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCreditsActionPerformed

    private void txtDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescriptionActionPerformed

    private void txtCourseNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCourseNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCourseNameActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow != -1) {
            txtCourseName.setText(jTable1.getValueAt(selectedRow, 1).toString()); // Course Name
            txtDescription.setText(jTable1.getValueAt(selectedRow, 2).toString()); // Description Name
            txtCredits.setText(jTable1.getValueAt(selectedRow, 3).toString()); // Credits

        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void EnrollmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnrollmentActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(() -> new EnrollmentManagementWindow().setVisible(true));
        this.dispose();
    }//GEN-LAST:event_EnrollmentActionPerformed

    private void StudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(() -> new StudentManagementWindow().setVisible(true));
        this.dispose();
    }//GEN-LAST:event_StudentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CourseManagementWindow().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private studentenrollmentsystem.RoundedButton Add;
    private studentenrollmentsystem.RoundedButton Delete;
    private studentenrollmentsystem.RoundedButton Enrollment;
    private studentenrollmentsystem.RoundedButton Student;
    private studentenrollmentsystem.RoundedButton Update;
    private studentenrollmentsystem.RoundedButton View;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private studentenrollmentsystem.RoundedPanel roundedPanel1;
    private studentenrollmentsystem.RoundedTextField txtCourseName;
    private studentenrollmentsystem.RoundedTextField txtCredits;
    private studentenrollmentsystem.RoundedTextField txtDescription;
    // End of variables declaration//GEN-END:variables

    private void clearFields() {
        txtCourseName.setText("");
        txtDescription.setText("");
        txtCredits.setText("");
        jTable1.clearSelection();
    }
}
