/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package studentenrollmentsystem;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asus
 */
public class EnrollmentManagementWindow extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EnrollmentManagementWindow.class.getName());

    private Connection getConnection() {
        return DBConnection.getConnection();

    }

    private void populateComboBoxes() {
        Combo1.removeAllItems();
        Combo2.removeAllItems();

        Connection conn = getConnection();

        // 1. ADD THIS SAFETY CHECK: If connection fails, stop here and don't crash!
        if (conn == null) {
            JOptionPane.showMessageDialog(this, "Could not connect to the database to load dropdowns.");
            return;
        }

        // 2. Safely run the queries
        try (Statement stmt = conn.createStatement()) {

            ResultSet rsStudent = stmt.executeQuery("SELECT student_id, first_name, last_name FROM student");
            while (rsStudent.next()) {
                Combo1.addItem(rsStudent.getInt("student_id") + " - " + rsStudent.getString("first_name") + " " + rsStudent.getString("last_name"));
            }

            ResultSet rsCourse = stmt.executeQuery("SELECT course_id, course_name FROM course");
            while (rsCourse.next()) {
                Combo2.addItem(rsCourse.getInt("course_id") + " - " + rsCourse.getString("course_name"));
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "SQL Error: " + e.getMessage());
            e.printStackTrace();
        } finally {
            // 3. Always close the connection when done!
            try {
                conn.close();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
    }

    /**
     * Creates new form EnrollmentManagementWindow
     */
    public EnrollmentManagementWindow() {
        initComponents();
        
        populateComboBoxes();

        jTable1.setBackground(java.awt.Color.WHITE);
        jScrollPane1.getViewport().setBackground(java.awt.Color.WHITE);
        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        jTable1.setShowVerticalLines(false);

        // 2. Force the empty space inside the scroll pane to be white
        // (This removes that gray block at the very bottom)
        jScrollPane1.getViewport().setBackground(java.awt.Color.WHITE);

        // 3. Strip the border from the ScrollPane via code just to be absolutely sure
        // (This removes the thin gray box around the entire table area)
        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder());

        jTable1.setShowVerticalLines(false);

        // 2. Create a clean, flat renderer for the Header
        javax.swing.table.DefaultTableCellRenderer headerRenderer = new javax.swing.table.DefaultTableCellRenderer();
        headerRenderer.setBackground(java.awt.Color.WHITE);
        headerRenderer.setForeground(new java.awt.Color(80, 80, 80)); // Matches your dark gray text
        headerRenderer.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 5, 10, 5)); // Adds padding, REMOVES vertical borders!
        headerRenderer.setHorizontalAlignment(javax.swing.JLabel.LEFT);

        // 3. Apply this clean style to the table header
        jTable1.getTableHeader().setDefaultRenderer(headerRenderer);

        // Optional: Make the header a bit taller to look more modern
        jTable1.getTableHeader().setPreferredSize(new java.awt.Dimension(0, 35));

        javax.swing.table.DefaultTableCellRenderer leftRenderer = new javax.swing.table.DefaultTableCellRenderer();
        leftRenderer.setHorizontalAlignment(javax.swing.JLabel.LEFT);
        leftRenderer.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 5)); // 5px cushion

        // Loop through EVERY column to apply the fix
        for (int i = 0; i < jTable1.getColumnCount(); i++) {
            jTable1.getColumnModel().getColumn(i).setCellRenderer(leftRenderer);
        }
        
        this.setLocationRelativeTo(null);

        ViewActionPerformed(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        roundedPanel2 = new studentenrollmentsystem.RoundedPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Combo1 = new javax.swing.JComboBox<>();
        Combo2 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        View = new studentenrollmentsystem.RoundedButton();
        jSeparator1 = new javax.swing.JSeparator();
        Delete = new studentenrollmentsystem.RoundedButton();
        Enroll = new studentenrollmentsystem.RoundedButton();
        Course = new studentenrollmentsystem.RoundedButton();
        Student = new studentenrollmentsystem.RoundedButton();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        roundedPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Enrollment Details");
        roundedPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 80, 123, 30));

        jLabel2.setText("Select Student");
        roundedPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 128, 87, 32));

        jLabel3.setText("Select Course");
        roundedPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 224, 101, 32));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Enrollment Management");
        roundedPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 6, 229, 47));

        Combo1.addActionListener(this::Combo1ActionPerformed);
        roundedPanel2.add(Combo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 166, 221, 40));

        Combo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BSECE", "BSCpE", "BSCE", " ", " " }));
        Combo2.addActionListener(this::Combo2ActionPerformed);
        roundedPanel2.add(Combo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 262, 221, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "E_ID", "Student Name", "Course Name", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        roundedPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 442, 370));

        View.setText("View");
        View.addActionListener(this::ViewActionPerformed);
        roundedPanel2.add(View, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 397, 96, 43));

        jSeparator1.setForeground(new java.awt.Color(220, 220, 220));
        roundedPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 59, 677, 15));

        Delete.setText("Delete");
        Delete.addActionListener(this::DeleteActionPerformed);
        roundedPanel2.add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 336, 96, 43));

        Enroll.setText("Enroll");
        Enroll.addActionListener(this::EnrollActionPerformed);
        roundedPanel2.add(Enroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 336, 96, 43));

        Course.setText("Course Form");
        Course.addActionListener(this::CourseActionPerformed);
        roundedPanel2.add(Course, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 450, 130, 40));

        Student.setText("Student Info");
        Student.addActionListener(this::StudentActionPerformed);
        roundedPanel2.add(Student, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 450, 130, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(roundedPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 754, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(roundedPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewActionPerformed
        // 1. Get the table model and clear out the old empty rows
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        // 2. The SQL JOIN: This grabs the IDs and translates them into actual Names!
        String query = "SELECT e.enrollment_id, s.first_name, s.last_name, c.course_name, e.enrollment_date " +
                       "FROM enrolled_subject e " +
                       "JOIN student s ON e.student_id = s.student_id " +
                       "JOIN course c ON e.course_id = c.course_id " + 
                       "ORDER BY e.enrollment_id ASC";
        // 3. Connect and fetch the data
        try (Connection conn = getConnection()) {
            if (conn == null) {
                JOptionPane.showMessageDialog(this, "Cannot connect to Database!");
                return;
            }

            try (Statement stmt = conn.createStatement(); ResultSet rs = stmt.executeQuery(query)) {

                // Loop through every saved enrollment and add it to the table
                while (rs.next()) {
                    int enrollId = rs.getInt("enrollment_id");
                    String studentName = rs.getString("first_name") + " " + rs.getString("last_name");
                    String courseName = rs.getString("course_name");
                    java.sql.Date enrollDate = rs.getDate("enrollment_date");

                    // Add the row to your jTable1
                    model.addRow(new Object[]{enrollId, studentName, courseName, enrollDate});
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error loading table: " + ex.getMessage());
            ex.printStackTrace(); // Prints the exact SQL error in the output box
        }
    }//GEN-LAST:event_ViewActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select an enrollment record to delete from the table.");
            return;
        }

// Get the enrollment_id from the first column (index 0) of the selected row
        int enrollmentId = (int) jTable1.getValueAt(selectedRow, 0);

        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to drop this student from the course?", "Confirm Deletion", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            try (Connection conn = getConnection(); PreparedStatement pst = conn.prepareStatement("DELETE FROM enrolled_subject WHERE enrollment_id=?")) {

                pst.setInt(1, enrollmentId);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Enrollment Deleted Successfully!");
                ViewActionPerformed(evt); // Refresh the table
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_DeleteActionPerformed

    private void EnrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnrollActionPerformed
        // TODO add your handling code here:

       
        // 1. Get the selected strings from the ComboBoxes
        String selectedStudent = (String) Combo1.getSelectedItem();
        String selectedCourse = (String) Combo2.getSelectedItem();

// Safety check: ensure something is actually selected
        if (selectedStudent == null || selectedCourse == null) {
            JOptionPane.showMessageDialog(this, "Please select both a student and a course!");
            return;
        }

        try {
            // 2. Extract the IDs from the text (Splits the string at " - " and takes the first part)
            int studentId = Integer.parseInt(selectedStudent.split(" - ")[0].trim());
            int courseId = Integer.parseInt(selectedCourse.split(" - ")[0].trim());

            // 3. Get the current date for the enrollment_date column
            java.sql.Date enrollmentDate = new java.sql.Date(System.currentTimeMillis());

            // 4. Prepare the SQL INSERT Statement
            // NOTE: If your table name in MySQL doesn't have a space, change `Enrolled Subject` to enrolled_subject
            String query = "INSERT INTO Enrolled_Subject (student_id, course_id, enrollment_date) VALUES (?, ?, ?)";

            // Execute the query using your database connection
            try (Connection conn = getConnection(); PreparedStatement pstmt = conn.prepareStatement(query)) {

                pstmt.setInt(1, studentId);
                pstmt.setInt(2, courseId);
                pstmt.setDate(3, enrollmentDate);

                int rowsInserted = pstmt.executeUpdate();

                if (rowsInserted > 0) {
                    JOptionPane.showMessageDialog(this, "Student enrolled successfully!");
                     ViewActionPerformed(null);

                    // 5. Refresh your table to show the new data
                    // Call whatever method you use to load data into jTable1 (e.g., viewEnrollments(); or loadData();)
                }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Database Error: " + ex.getMessage());
                ex.printStackTrace();
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error processing the selected data.");
            ex.printStackTrace();
        }
    }//GEN-LAST:event_EnrollActionPerformed

    private void Combo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Combo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Combo2ActionPerformed

    private void Combo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Combo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Combo1ActionPerformed

    private void CourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CourseActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(() -> new CourseManagementWindow().setVisible(true));
        this.dispose();
    }//GEN-LAST:event_CourseActionPerformed

    private void StudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(() -> new StudentManagementWindow().setVisible(true));
        this.dispose();
    }//GEN-LAST:event_StudentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EnrollmentManagementWindow().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Combo1;
    private javax.swing.JComboBox<String> Combo2;
    private studentenrollmentsystem.RoundedButton Course;
    private studentenrollmentsystem.RoundedButton Delete;
    private studentenrollmentsystem.RoundedButton Enroll;
    private studentenrollmentsystem.RoundedButton Student;
    private studentenrollmentsystem.RoundedButton View;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private studentenrollmentsystem.RoundedPanel roundedPanel2;
    // End of variables declaration//GEN-END:variables

}
